### ISSUE TITLE
MusicDB

### ISSUE THREAD

**Issue by thalerngsak-wi** [adadesions/MusicDB-TOT-2#2]
id
artist
music_name
rating 
Music_genre 
year
label

**Comment by adadesions** [comment]
**In conclusion,**
### Data format
{
"id":  string, id > 0 and id is natural number 
"music_name": string,
"music_genre":  string,
"artist":  string, 
"year": "string,
}

### Example,
{
"id": "0",
"music_name": "Melon Juice",
"music_genre": "Pop",
"artist": "CGM48, BNK48",
"year": "2020",
}
