### ISSUE TITLE
Fix error on music_db 2 case

### ISSUE THREAD

**Issue by bweerasakoutlook** [adadesions/MusicDB-TOT-2#20]
1. JSON Syntax error
2. ID: 2, lost year field

**Comment by PiyaratJ** [comment]
JSON Syntax error solved!

**Comment by adadesions** [comment]
This issue is duplicated with #18 , no need to open again

**Comment by PiyaratJ** [comment]
reopen issues

**Comment by bweerasakoutlook** [comment]
cleared issue
